SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[Sys_MarketingClaims_ProcessLog](
	[LogID] [int] IDENTITY(1,1) NOT NULL,
	[LogTime] [datetime] NULL,
	[Message] [varchar](4000) NULL,
	[UserName] [nvarchar](128) NULL,
 CONSTRAINT [PK_Sys_MarketingClaims_ProcessLog] PRIMARY KEY CLUSTERED 
(
	[LogID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90) ON [PRIMARY]
) ON [PRIMARY]
GO

